//! Append-only SQL snippets for catalog / physical DDL under `{migrations_dir}/generated/`.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use time::format_description::well_known::Rfc3339;
use time::OffsetDateTime;

use crate::logger::prelude::*;

use super::error::Result;

pub fn generated_dir(migrations_root: impl AsRef<Path>) -> PathBuf {
    migrations_root.as_ref().join("generated")
}

/// Writes a timestamped `.sql` file (best-effort). Failures are logged and do not abort storage ops.
pub fn try_write_generated_migration(
    migrations_root: &Path,
    entity: &str,
    action: &str,
    preamble: &str,
    sql_body: &str,
) {
    if let Err(e) = write_generated_migration(migrations_root, entity, action, preamble, sql_body) {
        warn!(
            "could not write generated schema migration for {} ({}): {}",
            entity, action, e
        );
    }
}

fn write_generated_migration(
    migrations_root: &Path,
    entity: &str,
    action: &str,
    preamble: &str,
    sql_body: &str,
) -> Result<()> {
    let ts = OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .unwrap_or_else(|_| "unknown-time".into());
    let safe_ts: String = ts
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    let dir = generated_dir(migrations_root);
    fs::create_dir_all(&dir)?;
    let fname = format!("{}_{}_{}.sql", safe_ts, sanitize_filename(entity), action);
    let path = dir.join(fname);
    let mut f = fs::File::create(&path)?;
    writeln!(f, "-- Generated by mantisbase at {ts}")?;
    writeln!(f, "-- entity: {entity}  action: {action}")?;
    if !preamble.trim().is_empty() {
        writeln!(f, "{}", preamble.trim_end())?;
        writeln!(f)?;
    }
    write!(f, "{}", sql_body.trim())?;
    if !sql_body.trim_end().ends_with(';') {
        writeln!(f, ";")?;
    } else {
        writeln!(f)?;
    }
    Ok(())
}

fn sanitize_filename(entity: &str) -> String {
    entity
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

pub fn format_schema_json_comment(doc: &serde_json::Value) -> String {
    let s = serde_json::to_string_pretty(doc).unwrap_or_else(|_| "{}".into());
    let mut out = String::from("-- catalog document (JSON):\n");
    for line in s.lines() {
        out.push_str("-- ");
        out.push_str(line);
        out.push('\n');
    }
    out
}
