//! Append-only SQL snippets for catalog / physical DDL under `{migrations_dir}/generated/`.
//! Each schema change writes a **pair** of files with the same timestamp stem:
//! `{ts}_{entity}_{action}_sqlite.sql` and `{ts}_{entity}_{action}_postgres.sql`, so operators can
//! replay migrations when moving between libSQL/SQLite and PostgreSQL.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use time::format_description::well_known::Rfc3339;
use time::OffsetDateTime;

use crate::logger::prelude::*;

use super::error::Result;

pub fn generated_dir(migrations_root: impl AsRef<Path>) -> PathBuf {
    migrations_root.as_ref().join("generated")
}

/// Join planned physical DDL lines for embedding in a migration file.
pub fn join_physical_ddl_statements(stmts: &[String]) -> String {
    if stmts.is_empty() {
        "-- no physical DDL statements (catalog metadata only)\n".to_string()
    } else {
        stmts.join("\n")
    }
}

/// Writes two timestamped files (SQLite/libSQL and PostgreSQL bodies). Best-effort; failures are logged.
pub fn try_write_generated_schema_migrations(
    migrations_root: &Path,
    entity: &str,
    action: &str,
    preamble: &str,
    sqlite_sql: &str,
    postgres_sql: &str,
) {
    if let Err(e) = write_generated_schema_migrations(
        migrations_root,
        entity,
        action,
        preamble,
        sqlite_sql,
        postgres_sql,
    ) {
        warn!(
            "could not write generated schema migrations for {} ({}): {}",
            entity, action, e
        );
    }
}

fn write_generated_schema_migrations(
    migrations_root: &Path,
    entity: &str,
    action: &str,
    preamble: &str,
    sqlite_sql: &str,
    postgres_sql: &str,
) -> Result<()> {
    let ts = OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .unwrap_or_else(|_| "unknown-time".into());
    let safe_ts: String = ts
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    let dir = generated_dir(migrations_root);
    fs::create_dir_all(&dir)?;
    let base = format!("{}_{}_{}", safe_ts, sanitize_filename(entity), action);
    write_one_generated_file(
        &dir.join(format!("{base}_sqlite.sql")),
        &ts,
        entity,
        action,
        "sqlite (libSQL)",
        preamble,
        sqlite_sql,
    )?;
    write_one_generated_file(
        &dir.join(format!("{base}_postgres.sql")),
        &ts,
        entity,
        action,
        "postgres",
        preamble,
        postgres_sql,
    )?;
    Ok(())
}

fn write_one_generated_file(
    path: &Path,
    ts: &str,
    entity: &str,
    action: &str,
    dialect_label: &str,
    preamble: &str,
    sql_body: &str,
) -> Result<()> {
    let mut f = fs::File::create(path)?;
    writeln!(f, "-- Generated by mantisbase at {ts}")?;
    writeln!(f, "-- dialect: {dialect_label}")?;
    writeln!(f, "-- entity: {entity}  action: {action}")?;
    if !preamble.trim().is_empty() {
        writeln!(f, "{}", preamble.trim_end())?;
        writeln!(f)?;
    }
    write!(f, "{}", sql_body.trim())?;
    if !sql_body.trim_end().ends_with(';') {
        writeln!(f, ";")?;
    } else {
        writeln!(f)?;
    }
    Ok(())
}

fn sanitize_filename(entity: &str) -> String {
    entity
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

pub fn format_schema_json_comment(doc: &serde_json::Value) -> String {
    let s = serde_json::to_string_pretty(doc).unwrap_or_else(|_| "{}".into());
    let mut out = String::from("-- catalog document (JSON):\n");
    for line in s.lines() {
        out.push_str("-- ");
        out.push_str(line);
        out.push('\n');
    }
    out
}
