site_name: MantisBase Documentation
site_url: https://mantisbase.com
site_description:  User and developer docs for navigating the use and integration of MantisBase, an open source, single-binary, lightweight BaaS toolkit written in C++.
site_author: MantisBase Team

docs_dir: content
site_dir: site

repo_url: https://github.com/allankoech/mantisbase/
edit_uri: blob/master/docs/

theme:
  name: material
  custom_dir: content/overrides
  logo: guides/assets/mantisbase.svg
  favicon: guides/assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
  palette:
    # Palette for dark mode
    - scheme: slate
      primary: grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
extra_css:
  - stylesheets/doxide.css
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/src/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/src/sorts/tablesort.number.js
  - javascripts/tablesort.js
nav:
  - Home: index.md
  - "Getting Started":
      - guides/installation.md
      - guides/docker.md
  - "Guides":
      - guides/cmd.md
      - guides/api.md
      - guides/auth.md
      - guides/embedding.md
      - guides/rules.md
      - guides/files.md
      - guides/healthcheck.md
      - guides/scripting.md
  - "C++ API Reference":
      - api/index.md
