name: CI

on:
  push:
    branches: [ "master", "v0.3.x" ]
  pull_request:
    branches: [ "master", "v0.3.x" ]

permissions:
  contents: read

jobs:
  rust:
    uses: ./.github/workflows/rust-ci.yml
